### ISSUE TITLE
requires that repo has a `scripts/get-image.sh` file

### ISSUE THREAD

**Issue by flynneva** [antmicro/renode-linux-runner-action#15]
Hey guys! Great effort here btw, I've been waiting for someone to come along and do this 😅 

While trying to test out this repo to [add some integration tests to `usb_cam` for ROS](https://github.com/ros-drivers/usb_cam/pull/242) it looks like there is an undocumented requirement as of today that the repo as a file `scripts/get-image.sh`...which i'm not sure is intended.

**Comment by WiktorOgrodnik** [comment]
Hi, thanks for your comment.

I accidentally made a mistake in our action, by assuming that the additional scripts that we use in it are also available from external repositories.

However, there is a simple fix for this, github copies the action repository and puts it under the ${{github.action_path}} path, so all we need to do is replace the scripts/get-image.sh path with ${{github.action_path}}/scripts/get-image.sh and so on.

I have fixed this problem on our local fork: https://github.com/antmicro-labs/renode-linux-runner-action/tree/disable-multicore-emulation and it will probably be merged into the main repo soon.

**Comment by flynneva** [comment]
@WiktorOgrodnik you're awesome! thanks again 🙏🏼
